
// This file is automatically created by parse_maestro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

pp.query("stop_time", stop_time);
pp.query("max_step", max_step);
pp.query("cflfac", cflfac);
pp.query("regrid_int", regrid_int);
pp.query("plot_int", plot_int);
pp.query("plot_base_name", plot_base_name);
pp.query("do_reflux", do_reflux);
