
// This file is automatically created by parse_maestro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static std::string model_file;
static int perturb_model;
static int print_init_hse_diag;
static amrex::Real stop_time;
static int max_step;
static amrex::Real cflfac;
static int regrid_int;
static int plot_int;
static std::string plot_base_name;
static int do_reflux;
static amrex::Real small_temp;
static amrex::Real small_dens;
static int use_tfromp;
static int use_eos_e_instead_of_h;
static int use_pprime_in_tfromp;
