
// This file is automatically created by parse_maestro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static amrex::Real stop_time;
static int max_step;
static amrex::Real cflfac;
static int regrid_int;
static int plot_int;
static std::string plot_base_name;
static int init_iter;
static int init_divu_iter;
static int restart;
static int restart_into_finer;
static int do_initial_projection;
static int do_reflux;
