#!/bin/bash
#PBS -A ast106
#PBS -N xrb-768-OMP4
#PBS -j oe
#PBS -l walltime=0:30:00,nodes=1024
#PBS -q debug
#PBS -l gres=atlas1%atlas2

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=4

# -n number of MPI tasks
# -N number of PEs per node 
# -d number of CPUs per PE -- this should be the number of threads
# -j number of CPUs to use per compute unit (since 2 PE share an FPU, we may want to reduce this)
aprun -n 4096 -N 4 -d 4 -j 2 ./main.Linux.Cray.mpi.omp.exe inputs_3d_6.0cm.hi_dens
