name: GPU compilation

on: [pull_request]

jobs:
  gpu-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Install CUDA
        run: .github/workflows/dependencies/dependencies_nvcc.sh 11.8

      - name: Compile reacting_bubble for GPU
        run: |
          export PATH=$PATH:/usr/local/cuda/bin
          cd Exec/test_problems/reacting_bubble
          make DIM=2 USE_MPI=FALSE USE_CUDA=TRUE -j 4
