name: wdconvect

on: [pull_request]
jobs:
  wdconvect-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl g++>=9.3.0

      - name: Compile wdconvect
        run: |
          cd Exec/science/wdconvect
          make USE_OMP=FALSE USE_MPI=FALSE -j 4

      - name: Run wdconvect
        run: |
          cd Exec/science/wdconvect
          cp model_files/kepler_new_6.25e8.hybrid.hse.320 .
          cp inputs_files/inputs_3d_regression.2levels .
          ./Maestro3d.gnu.ex inputs_3d_regression.2levels

      - name: Build the fextrema tool
        run: |
          cd external/amrex/Tools/Plotfile
          make programs=fextrema -j 4

      - name: Check the extrema
        run: |
          cd Exec/science/wdconvect
          ../../../external/amrex/Tools/Plotfile/fextrema.gnu.ex wdconvect_plt0000003 > fextrema.out
          diff fextrema.out ci-benchmarks/wdconvect_3d_extrema.out

